language = "golang"
status = "pre-alpha"

[documentation]
description  = "golang driver for [babelfish](https://github.com/bblfsh/server)."

[runtime]
os = "alpine"
go_version = "1.9.2"
native_version = ["1.9.2"]